apiVersion: apps/v1
kind: Deployment
metadata:
  name: brandon01
spec:
  selector:
    matchLabels:
      app: brandon01-pod
  template:
    metadata:
      labels:
        app: brandon01-pod
    spec:
      containers:
      - name: brandon01-container
        image: bcglabacr01.azurecr.io/workingwithacr:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
